services:
  nginx:
    image: nginx:latest
    container_name: transcendence_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - transcendence_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - transcendence_network

networks:
  transcendence_network:
    driver: bridge
